#!/usr/bin/env bash
# This script transfers a file from the client to a server using SCP

if [ ${#} -eq 4 ];

then

  PATH_TO_FILE="${1}"
  SERVER_IP="${2}"
  USERNAME="${3}"
  PATH_TO_SSH_KEY="${4}"

  scp -o StrictHostKeyChecking=no -i "${PATH_TO_SSH_KEY}" "${PATH_TO_FILE}" "${USERNAME}"@"${IP}":~/

else
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
