#!/bin/env bash

# Edit the hosts file to resolve localhost to 127.0.0.2
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts

# Edit the hosts file to resolve facebook.com to 8.8.8.8
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
